### PR TITLE
PageBackdrop component

### LINKED ISSUE #24: Update Background for each section to match with design
Design: Figma / Stylesheet

### PR DESCRIPTION
**Pull request by ken-centrality**
## Description

Implement `PageBackdrop` component which changes colors and graphics when switching to different sections

Closes #24, #25

#### Changes

- Reformat the `css` files using `prettier`
- Rename all css files with title case to match with their binding components
- Apply a slight round corner for top navigation and main panel
- Tidy up `public` folders, move all svgs into `public/images` folder
- Move pages related CSS files into `styles/pages` folder

#### Removes

- Remove usage of `Teko` fonts

#### Adds

- Add `pool.module.css` to apply general styling for Pool section
- Add `sass` package to allow styling using SCSS
- Add `PageBackdrop` component

### CODE REVIEW

**Review by aidan-starke — APPROVED** [review]
looks awesome!

One thing (maybe not part of this PR) - would we prefer to have the pool and bridge components floating (not touching the bottom of the screen)?

**Comment by eupston** [comment]
yeah maybe we could make it so it always fills the window height when bridge and pool components force height offscreen?

https://user-images.githubusercontent.com/35315320/155208985-736bbac0-ae2f-4117-b6a6-1da05d0b2c8d.mov



otherwise end up with overlap on switch and components:


Screen Shot 2022-02-22 at 12 57 04 PM
Screen Shot 2022-02-22 at 12 58 04 PM

**Comment by ken-centrality** [comment]
updated the branch with 2 changes

- Make the main panel scroll-able underneath the border frame
- Switch out different graphics for each element

There is one more thing I'd like to address is the hover state of AppSwitch as mentioned by @eupston but will do that once @aidan-starke AppSwitch work is merge to avoid more conflict

**Comment by ken-centrality** [comment]
@aidan-starke FYI, check out the commit 4157f82, saw this warning about the prop `tx` so I made some changes to `AppSwitch`

```
Warning: Failed prop type: Invalid prop `sx` supplied to `ForwardRef(Button)`, expected one of type [function, object].
    at Button (/Users/ken/Workspace/CENNZnet/app-hub/node_modules/@mui/material/node/Button/Button.js:246:30)
    at /Users/ken/Workspace/CENNZnet/app-hub/node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:51:25
    at Link (webpack-internal:///./node_modules/next/dist/client/link.js:63:23)
    at div
    at /Users/ken/Workspace/CENNZnet/app-hub/node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:51:25
```

Plus I'd like to stick the same approach of using props to change the style rather having `sx` as well as Styled Component

**Comment by ken-centrality** [comment]
@eupston have another spin and give me the 👍  if you are happy so I can merge this! Thanks!

**Review by eupston — APPROVED** [review]
looks great!!

**Review by eupston — COMMENTED** [review]
actually sorry @ken-centrality looks like small issue with margins on bridge here

Screen Shot 2022-02-22 at 4 31 02 PM

**Pull request merged**
