### PR TITLE
edit cennz wallet / metamask button

### PR DESCRIPTION
**Pull request by aidan-starke**
CENNZ wallet now global
Connect MetaMask button now on bridge page - removed connect page

### CODE REVIEW

**Review by eupston — APPROVED** [review]
lgtm!

**Review by ken-centrality — COMMENTED** [review]
@aidan-starke couple of things
- I have to click on "Connect Metamask" again after the Metamask plugin prompt me to connect with the domain. Can we avoid it?
- Can we prompt user to connect to CENNZnet if user hasn't after Metamask is connected?

**Comment by aidan-starke** [comment]
> @aidan-starke couple of things
> 
> * I have to click on "Connect Metamask" again after the Metamask plugin prompt me to connect with the domain. Can we avoid it?
> * Can we prompt user to connect to CENNZnet if user hasn't after Metamask is connected?

I couldn't get this issue to happen with MetaMask, but I've changed CENNZnet wallet so it default selects 1st account (avoids having to click button twice) - it may also mean the next two things aren't necessary:

- Connect MetaMask button can now operate as a Connect Wallets button
- User is prompted to connect CENNZnet if they haven't before switching to withdraw

**Review by ken-centrality — APPROVED** [review]
That Metamask issue that I experienced has disappeared so LGTM!

**Pull request merged**
